### ISSUE TITLE
Looks great, could you expand the readme a bit?

### ISSUE THREAD

**Issue by nielsrobin** [Mattie112/FactoriGOChatBot#1]
Hi, this looks great and I want to try it on my factorio server, however I'm not sure how to set it up.

The .env file, how to I run it with the exe? does it take some kind of parameter? Like "factorigo-chat-bot --env settings.env" ?
(on windows btw, and I'd like to avoid adding these directly to the environment variables OS).

**Comment by Mattie112** [comment]
Hi there!

Thank you for looking at my bot. I did try to write a bit of a readme but as I'm still working on the bot I can agree it is not 100% up2date.

I myself run the docker version. For the windows/linux binary it should be enough to have a `.env` file in the same directory as the executable. Or you can make a .bat file like so:

```
set LOG_LEVEL=info
set DISCORD_TOKEN=xx
(etc)
factorigo-chat-bot.exe
```

I do want to expand the readme on how exactly to setup the discord bot but it should be roughly: https://discordpy.readthedocs.io/en/stable/discord.html

Do you already have the bot created? And the tokens? I might need to try and set it up from scratch myself :)

And with regards to the factorio server. Yes you need to set the rcon port / password. I use FactorioServerManager so I would need to look up the exact flags. I think it would be:

```
--rcon-port xxx
--rcon password xxx
--console-log /path/to/some/file
```

The console-log option will output the chat into a separate file. On Linux I had some issues if I didn't do this but it might work on Windows.

Please let me know what you find then I can expand the readme :) I'm not 100% if I have time tonight to try it out myself. If I do I'll let you know!

**Comment by nielsrobin** [comment]
Fantastic, this should be plenty for me to work with.. thanks for the --clonsole-log bit, I'd completely missed that

**Comment by nielsrobin** [comment]
Hopefully last question. Got the bot configured and added to Discord. Using this guide:
https://www.writebots.com/discord-bot-token/

Got everything running, and sucessfully tested a message from the factorio server to the discord channel.

However the other way around, whenever I type something into the discord channel, instead of it being displayed in the factorio server, I see this:
"274.628 Info RemoteCommandProcessor.cpp:249: New RCON connection from IP ADDR:({10.0.30.33:60996})"

Any Idea what I might be missing?

![image](https://user-images.githubusercontent.com/1383483/156184465-d62fa7cd-0b99-439b-a625-b2607010e7a0.png)

**Comment by Mattie112** [comment]
> This might also just be me, since I'm unfamiliar with GoLang, but it took me forever to realize the file should be named ".env" without anything infront of the extension.

Yeah perhaps it would be clearer to name it 'config.txt' or something :) I'm used to having .env files so yeah :) I will see what I can do (with either expanding the README or changing it)

**Comment by Mattie112** [comment]
> Hopefully last question. Got the bot configured and added to Discord. Using this guide: https://www.writebots.com/discord-bot-token/
> 
> Got everything running, and sucessfully tested a message from the factorio server to the discord channel.
> 
> However the other way around, whenever I type something into the discord channel, instead of it being displayed in the factorio server, I see this: "274.628 Info RemoteCommandProcessor.cpp:249: New RCON connection from IP ADDR:({10.0.30.33:60996})"
> 
> Any Idea what I might be missing?
> 
> ![image](https://user-images.githubusercontent.com/1383483/156184465-d62fa7cd-0b99-439b-a625-b2607010e7a0.png)

Could you set LOG_LEVEL to debug? Just to get an better idea what the bot is doing.

**Comment by nielsrobin** [comment]
Hm, looking at this, it actually looks like it's doing it right.

![image](https://user-images.githubusercontent.com/1383483/156185847-13df3b55-c91d-4f41-a4fe-4785d60a97e3.png)

**Comment by nielsrobin** [comment]
Maybe it is working I just cannot see it in the server console?

![image](https://user-images.githubusercontent.com/1383483/156186764-a38d9a11-39c3-401c-a9e7-64fd5e8c5731.png)

**Comment by Mattie112** [comment]
Hm that could be the case, not sure. I always tested it in the game.

I will also make an option to not use `silent-command` but the 'regular' message. That should not disable achievements (or so I was told) but will look a bit worse. (Always white in the form of "<server> ......"

**Comment by nielsrobin** [comment]
> Hm that could be the case, not sure. I always tested it in the game.
> 
> I will also make an option to not use `silent-command` but the 'regular' message. That should not disable achievements (or so I was told) but will look a bit worse. (Always white in the form of `"<server> ......"`)

Makes sense, I'll test it ingame when I get home today.

**Comment by nielsrobin** [comment]
Confirmed, works ingame no problem! Thanks mate, let me know if you need any help testing new features in the future.

**Comment by Mattie112** [comment]
Nice! I'll update the README in a bit with the new insights. If you have anything to add please let me know or create a PR. I'm still planning to fix somethings (like mentions are shown as `@12309723497234` in Factorio). But if you have more suggestions let me know :). Did you also see the companion mod that adds support for stuff like deaths / research?

**Comment by Mattie112** [comment]
Hope I made it a bit clearer ;)

https://github.com/Mattie112/FactoriGOChatBot/commit/e5ae4ccae01f270b92c430e2bb87a01bcc912e9d

**Comment by nielsrobin** [comment]
> Hope I made it a bit clearer ;)
> 
> [e5ae4cc](https://github.com/Mattie112/FactoriGOChatBot/commit/e5ae4ccae01f270b92c430e2bb87a01bcc912e9d)

Looks great thanks and yes just installed the companion mod, so will be testing that tonight.
