### ISSUE TITLE
RCON_IP no longer accepts textual DNS names

### ISSUE THREAD

**Issue by gavento** [Mattie112/FactoriGOChatBot#30]
Change 28b880b adds explicit IP parsing with `net.ParseIP` which only accepts numeric addresses. The previous code also allowed DNS names (resolved automatically to the actual IP in `rcon.New`), which was very convenient in settings with dynamic IP addresses. Could we please have it back? :-)

Thanks for all the great work on the bot!

**Comment by Mattie112** [comment]
Ah, that's a feature I didn't think about :) Yes changing it back to a string is fine by me!

**Comment by Mattie112** [comment]
I think this should work: https://github.com/Mattie112/FactoriGOChatBot/pull/31
