### ISSUE TITLE
Bot can't handle "-" character for join and leave events

### ISSUE THREAD

**Issue by MrManz** [Mattie112/FactoriGOChatBot#43]
Dear maintainer,

thanks you very much for your work.
I found that the bot does not handle the "-" char correctly for join and leave events.
Could you have a look and maybe fix this?

Many Thanks

![Screenshot from 2024-12-11 12-09-32](https://github.com/user-attachments/assets/e25a2606-aa1b-405a-8090-5bc897beb9ff)

**Comment by Mattie112** [comment]
Oh that is an interesting one :) Thanks for the report I will look into it!
